import { GameWorld, GameLevel, Character, Difficulty } from './types'

// ==================== 世界配置 ====================
export const GAME_WORLDS: GameWorld[] = [
  {
    id: 'world1',
    name: '甜甜加法森林',
    emoji: '🌸',
    color: '#ff6699',
    colorLight: '#ffe8f0',
    description: '加法从这里开始！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world2',
    name: '神秘减法洞穴',
    emoji: '🌟',
    color: '#9b59b6',
    colorLight: '#f3e5f5',
    description: '减法探险之旅！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world3',
    name: '乘法水晶矿',
    emoji: '✨',
    color: '#3498db',
    colorLight: '#e8f4fd',
    description: '开启速算超能力！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world4',
    name: '除法魔法塔',
    emoji: '🔮',
    color: '#e67e22',
    colorLight: '#fef3e2',
    description: '挑战除法奥秘！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world5',
    name: '速算大师赛',
    emoji: '🏆',
    color: '#e74c3c',
    colorLight: '#fdecea',
    description: '综合挑战，速算之王！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
]

// ==================== 关卡配置 ====================
export const GAME_LEVELS: GameLevel[] = [
  // ===== 世界1：加法森林 =====
  {
    id: 'world1-level1',
    worldId: 'world1',
    order: 1,
    name: '水果加法',
    description: '10以内数字相加',
    difficulty: 'ADD2to2',
    questionCount: 10,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 5, diamonds: 1 },
    unlockCost: 0,
  },
  {
    id: 'world1-level2',
    worldId: 'world1',
    order: 2,
    name: '两位数探险',
    description: '整十数加法',
    difficulty: 'ADD2to2',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 5,
    requiredLevel: 'world1-level1',
  },
  {
    id: 'world1-level3',
    worldId: 'world1',
    order: 3,
    name: '三位数挑战',
    description: '三位数加两位数',
    difficulty: 'ADD2to3',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 15,
    requiredLevel: 'world1-level2',
  },
  {
    id: 'world1-level4',
    worldId: 'world1',
    order: 4,
    name: '四位数冲刺',
    description: '四位数加减法',
    difficulty: 'ADD3to4',
    questionCount: 10,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 30,
    requiredLevel: 'world1-level3',
  },
  {
    id: 'world1-level5',
    worldId: 'world1',
    order: 5,
    name: '加法森林BOSS',
    description: '混合加法，速度挑战！',
    difficulty: 'ADD4to4',
    questionCount: 15,
    timeLimit: 20,
    starThresholds: [90, 75],
    reward: { stars: 20, diamonds: 5 },
    unlockCost: 50,
    requiredLevel: 'world1-level4',
  },

  // ===== 世界2：减法洞穴 =====
  {
    id: 'world2-level1',
    worldId: 'world2',
    order: 1,
    name: '减法入门',
    description: '两位数减法',
    difficulty: 'SUB2to2',
    questionCount: 10,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 5, diamonds: 1 },
    unlockCost: 0,
  },
  {
    id: 'world2-level2',
    worldId: 'world2',
    order: 2,
    name: '不退位减法',
    description: '三位数减法',
    difficulty: 'SUB3to3',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 5,
    requiredLevel: 'world2-level1',
  },
  {
    id: 'world2-level3',
    worldId: 'world2',
    order: 3,
    name: '退位挑战',
    description: '三位数减法（退位）',
    difficulty: 'SUB3to3',
    questionCount: 12,
    timeLimit: 22,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 15,
    requiredLevel: 'world2-level2',
  },
  {
    id: 'world2-level4',
    worldId: 'world2',
    order: 4,
    name: '四位数减法',
    description: '四位数减法',
    difficulty: 'SUB3to4',
    questionCount: 10,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 30,
    requiredLevel: 'world2-level3',
  },
  {
    id: 'world2-level5',
    worldId: 'world2',
    order: 5,
    name: '减法洞穴BOSS',
    description: '混合减法，速度挑战！',
    difficulty: 'SUB4to4',
    questionCount: 15,
    timeLimit: 20,
    starThresholds: [90, 75],
    reward: { stars: 20, diamonds: 5 },
    unlockCost: 50,
    requiredLevel: 'world2-level4',
  },

  // ===== 世界3：乘法水晶矿 =====
  {
    id: 'world3-level1',
    worldId: 'world3',
    order: 1,
    name: '乘法口诀',
    description: '1~9乘法练习',
    difficulty: 'MULTIPLY_1to9',
    questionCount: 10,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 5, diamonds: 1 },
    unlockCost: 0,
  },
  {
    id: 'world3-level2',
    worldId: 'world3',
    order: 2,
    name: '乘5速算',
    description: '快速乘以5的技巧',
    difficulty: 'MULTIPLY_5',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 5,
    requiredLevel: 'world3-level1',
  },
  {
    id: 'world3-level3',
    worldId: 'world3',
    order: 3,
    name: '乘9速算',
    description: '快速乘以9的技巧',
    difficulty: 'MULTIPLY_9',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 15,
    requiredLevel: 'world3-level2',
  },
  {
    id: 'world3-level4',
    worldId: 'world3',
    order: 4,
    name: '平方数',
    description: '尾数5的平方 + 11~19平方',
    difficulty: 'SQUARE_END5',
    questionCount: 12,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 15, diamonds: 3 },
    unlockCost: 30,
    requiredLevel: 'world3-level3',
  },
  {
    id: 'world3-level5',
    worldId: 'world3',
    order: 5,
    name: '乘法BOSS战',
    description: '综合乘法挑战！',
    difficulty: 'MULTIPLY_11',
    questionCount: 15,
    timeLimit: 20,
    starThresholds: [90, 75],
    reward: { stars: 25, diamonds: 6 },
    unlockCost: 50,
    requiredLevel: 'world3-level4',
  },

  // ===== 世界4：除法魔法塔 =====
  {
    id: 'world4-level1',
    worldId: 'world4',
    order: 1,
    name: '除法入门',
    description: '除5速算技巧',
    difficulty: 'DIVIDE_5',
    questionCount: 10,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 0,
  },
  {
    id: 'world4-level2',
    worldId: 'world4',
    order: 2,
    name: '凑整加法',
    description: '凑整速算加法',
    difficulty: 'COMPENSATE_ADD',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 20,
    requiredLevel: 'world4-level1',
  },
  {
    id: 'world4-level3',
    worldId: 'world4',
    order: 3,
    name: '头同尾补',
    description: '十位相同个位和为10',
    difficulty: 'SAME_TENS_DIFF_ONES',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 15, diamonds: 3 },
    unlockCost: 40,
    requiredLevel: 'world4-level2',
  },
  {
    id: 'world4-level4',
    worldId: 'world4',
    order: 4,
    name: '11~19平方',
    description: '特殊平方数速算',
    difficulty: 'SPECIAL_SQUARE',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 15, diamonds: 3 },
    unlockCost: 60,
    requiredLevel: 'world4-level3',
  },
  {
    id: 'world4-level5',
    worldId: 'world4',
    order: 5,
    name: '速算大师BOSS',
    description: '全技巧综合挑战！',
    difficulty: 'MULTIPLY_11',
    questionCount: 20,
    timeLimit: 18,
    starThresholds: [90, 75],
    reward: { stars: 30, diamonds: 8 },
    unlockCost: 100,
    requiredLevel: 'world4-level4',
  },

  // ===== 世界5：综合大师赛 =====
  {
    id: 'world5-level1',
    worldId: 'world5',
    order: 1,
    name: '青铜挑战',
    description: '加减法混合',
    difficulty: 'ADD3to3',
    questionCount: 15,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 0,
  },
  {
    id: 'world5-level2',
    worldId: 'world5',
    order: 2,
    name: '白银挑战',
    description: '乘除法混合',
    difficulty: 'MULTIPLY_5',
    questionCount: 15,
    timeLimit: 22,
    starThresholds: [100, 80],
    reward: { stars: 15, diamonds: 4 },
    unlockCost: 50,
    requiredLevel: 'world5-level1',
  },
  {
    id: 'world5-level3',
    worldId: 'world5',
    order: 3,
    name: '黄金挑战',
    description: '速算技巧混合',
    difficulty: 'SQUARE_END5',
    questionCount: 15,
    timeLimit: 22,
    starThresholds: [100, 80],
    reward: { stars: 20, diamonds: 5 },
    unlockCost: 100,
    requiredLevel: 'world5-level2',
  },
  {
    id: 'world5-level4',
    worldId: 'world5',
    order: 4,
    name: '钻石挑战',
    description: '四位数混合运算',
    difficulty: 'ADD4to4',
    questionCount: 15,
    timeLimit: 20,
    starThresholds: [90, 75],
    reward: { stars: 25, diamonds: 6 },
    unlockCost: 150,
    requiredLevel: 'world5-level3',
  },
  {
    id: 'world5-level5',
    worldId: 'world5',
    order: 5,
    name: '王者之战',
    description: '全能王挑战！',
    difficulty: 'MULTIPLY_11',
    questionCount: 25,
    timeLimit: 15,
    starThresholds: [85, 70],
    reward: { stars: 50, diamonds: 15 },
    unlockCost: 250,
    requiredLevel: 'world5-level4',
  },
]

// ==================== 角色配置 ====================
export const CHARACTERS: Character[] = [
  {
    id: 'meiledi',
    name: '美乐蒂',
    emoji: '🐰',
    description: '可爱的粉色小兔，稳定发挥！',
    cost: 0,
    bonus: 'extra_time',
    bonusValue: 0,
  },
  {
    id: 'bear',
    name: '小棕熊',
    emoji: '🐻',
    description: '每题额外+3秒思考时间',
    cost: 20,
    bonus: 'extra_time',
    bonusValue: 3,
  },
  {
    id: 'fox',
    name: '智慧狐狸',
    emoji: '🦊',
    description: 'Combo奖励效果+50%',
    cost: 40,
    bonus: 'combo_boost',
    bonusValue: 0.5,
  },
  {
    id: 'dragon',
    name: '数学龙',
    emoji: '🐉',
    description: '所有奖励+25%',
    cost: 80,
    bonus: 'reward_boost',
    bonusValue: 0.25,
  },
]

export function getWorldLevels(worldId: string): GameLevel[] {
  return GAME_LEVELS.filter(l => l.worldId === worldId).sort((a, b) => a.order - b.order)
}

export function getLevelById(levelId: string): GameLevel | undefined {
  return GAME_LEVELS.find(l => l.id === levelId)
}

export function getLevelStars(levelId: string, correct: number, total: number): 0 | 1 | 2 | 3 {
  const level = getLevelById(levelId)
  if (!level) return 0
  const rate = total > 0 ? (correct / total) * 100 : 0
  if (rate >= level.starThresholds[0]) return 3
  if (rate >= level.starThresholds[1]) return 2
  if (rate >= 50) return 1
  return 0
}

export function isLevelUnlocked(levelId: string, user: { levelProgress: Record<string, number> }): boolean {
  const level = getLevelById(levelId)
  if (!level) return false
  if (level.unlockCost === 0 && !level.requiredLevel) return true

  // 检查前置关卡
  if (level.requiredLevel) {
    const progress = user.levelProgress[level.worldId] || 0
    const requiredOrder = getLevelById(level.requiredLevel)?.order || 0
    if (progress < requiredOrder) return false
  }
  return true
}

export function getCharacterById(id: string): Character | undefined {
  return CHARACTERS.find(c => c.id === id)
}
