import { GameWorld, GameLevel, Character, Difficulty } from './types'

// ==================== 世界配置 ====================
// 世界顺序与整体难度递增一致：
// 两位数加减 → 表内乘除 → 口算技巧 → 三位数加减 → 综合/拓展
export const GAME_WORLDS: GameWorld[] = [
  {
    id: 'world1',
    name: '两位数加减冒险岛',
    emoji: '🌺',
    color: '#ff6699',
    colorLight: '#ffe8f0',
    description: '先从两位数加减练起，打好基础！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world2',
    name: '表内乘除王国',
    emoji: '🌸',
    color: '#3498db',
    colorLight: '#e8f4fd',
    description: '乘法口诀 + 表内除法，速度起飞！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world3',
    name: '口算技巧训练营',
    emoji: '✨',
    color: '#9b59b6',
    colorLight: '#f3e5f5',
    description: '掌握技巧，算得又快又准！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world4',
    name: '三位数加减挑战区',
    emoji: '🌻',
    color: '#e67e22',
    colorLight: '#fef3e2',
    description: '进阶到三位数加减，稳步升级！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
  {
    id: 'world5',
    name: '高手进阶赛',
    emoji: '🏆',
    color: '#e74c3c',
    colorLight: '#fdecea',
    description: '规律乘除 + 综合挑战，冲刺速算大师！',
    levels: [],
    unlockCost: 0,
    isUnlocked: () => true,
  },
]

// ==================== 关卡配置 ====================
export const GAME_LEVELS: GameLevel[] = [
  // ===== 世界1：两位数加减（入门） =====
  {
    id: 'world1-level1',
    worldId: 'world1',
    order: 1,
    name: '两位数加法入门',
    description: '两位数加法（10~99）',
    difficulty: 'ADD2to2',
    questionCount: 10,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 5, diamonds: 1 },
    unlockCost: 0,
  },
  {
    id: 'world1-level2',
    worldId: 'world1',
    order: 2,
    name: '两位数减法入门',
    description: '两位数减法（保证为正）',
    difficulty: 'SUB2to2',
    questionCount: 12,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 5,
    requiredLevel: 'world1-level1',
  },
  {
    id: 'world1-level3',
    worldId: 'world1',
    order: 3,
    name: '两位数加法进阶',
    description: '两位数加法（速度挑战）',
    difficulty: 'ADD2to2',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 15,
    requiredLevel: 'world1-level2',
  },
  {
    id: 'world1-level4',
    worldId: 'world1',
    order: 4,
    name: '两位数减法进阶',
    description: '两位数减法（速度挑战）',
    difficulty: 'SUB2to2',
    questionCount: 10,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 30,
    requiredLevel: 'world1-level3',
  },
  {
    id: 'world1-level5',
    worldId: 'world1',
    order: 5,
    name: '两位数加减BOSS',
    description: '两位数加减综合（加法）',
    difficulty: 'ADD2to2',
    questionCount: 15,
    timeLimit: 22,
    starThresholds: [90, 75],
    reward: { stars: 20, diamonds: 5 },
    unlockCost: 50,
    requiredLevel: 'world1-level4',
  },

  // ===== 世界2：表内乘除法 =====
  {
    id: 'world2-level1',
    worldId: 'world2',
    order: 1,
    name: '乘法口诀',
    description: '1~9 乘法练习',
    difficulty: 'MULTIPLY_1to9',
    questionCount: 10,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 5, diamonds: 1 },
    unlockCost: 0,
  },
  {
    id: 'world2-level2',
    worldId: 'world2',
    order: 2,
    name: '表内除法',
    description: '1~9 表内除法（整除）',
    difficulty: 'DIVIDE_TABLE',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 5,
    requiredLevel: 'world2-level1',
  },
  {
    id: 'world2-level3',
    worldId: 'world2',
    order: 3,
    name: '乘法进阶',
    description: '乘法口诀（速度提升）',
    difficulty: 'MULTIPLY_1to9',
    questionCount: 12,
    timeLimit: 22,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 15,
    requiredLevel: 'world2-level2',
  },
  {
    id: 'world2-level4',
    worldId: 'world2',
    order: 4,
    name: '除法进阶',
    description: '表内除法（速度提升）',
    difficulty: 'DIVIDE_TABLE',
    questionCount: 10,
    timeLimit: 22,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 30,
    requiredLevel: 'world2-level3',
  },
  {
    id: 'world2-level5',
    worldId: 'world2',
    order: 5,
    name: '表内乘除BOSS',
    description: '表内乘法（挑战）',
    difficulty: 'MULTIPLY_1to9',
    questionCount: 15,
    timeLimit: 20,
    starThresholds: [90, 75],
    reward: { stars: 20, diamonds: 5 },
    unlockCost: 50,
    requiredLevel: 'world2-level4',
  },

  // ===== 世界3：口算技巧 =====
  {
    id: 'world3-level1',
    worldId: 'world3',
    order: 1,
    name: '凑整加法',
    description: '凑整速算加法',
    difficulty: 'COMPENSATE_ADD',
    questionCount: 10,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 8, diamonds: 2 },
    unlockCost: 0,
  },
  {
    id: 'world3-level2',
    worldId: 'world3',
    order: 2,
    name: '乘5速算',
    description: '快速乘以5的技巧',
    difficulty: 'MULTIPLY_5',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 20,
    requiredLevel: 'world3-level1',
  },
  {
    id: 'world3-level3',
    worldId: 'world3',
    order: 3,
    name: '乘9速算',
    description: '快速乘以9的技巧',
    difficulty: 'MULTIPLY_9',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 40,
    requiredLevel: 'world3-level2',
  },
  {
    id: 'world3-level4',
    worldId: 'world3',
    order: 4,
    name: '乘11速算',
    description: '两位数乘11技巧',
    difficulty: 'MULTIPLY_11',
    questionCount: 12,
    timeLimit: 25,
    starThresholds: [100, 80],
    reward: { stars: 15, diamonds: 3 },
    unlockCost: 60,
    requiredLevel: 'world3-level3',
  },
  {
    id: 'world3-level5',
    worldId: 'world3',
    order: 5,
    name: '技巧BOSS',
    description: '平方数速算（尾数5）',
    difficulty: 'SQUARE_END5',
    questionCount: 15,
    timeLimit: 22,
    starThresholds: [90, 75],
    reward: { stars: 25, diamonds: 6 },
    unlockCost: 100,
    requiredLevel: 'world3-level4',
  },

  // ===== 世界4：三位数加减 =====
  {
    id: 'world4-level1',
    worldId: 'world4',
    order: 1,
    name: '三位数加两位数',
    description: '三位数 + 两位数',
    difficulty: 'ADD2to3',
    questionCount: 10,
    timeLimit: 30,
    starThresholds: [100, 80],
    reward: { stars: 10, diamonds: 2 },
    unlockCost: 0,
  },
  {
    id: 'world4-level2',
    worldId: 'world4',
    order: 2,
    name: '三位数减两位数',
    description: '三位数 - 两位数',
    difficulty: 'SUB2to3',
    questionCount: 12,
    timeLimit: 28,
    starThresholds: [100, 80],
    reward: { stars: 12, diamonds: 3 },
    unlockCost: 20,
    requiredLevel: 'world4-level1',
  },
  {
    id: 'world4-level3',
    worldId: 'world4',
    order: 3,
    name: '三位数加法',
    description: '三位数 + 三位数',
    difficulty: 'ADD3to3',
    questionCount: 12,
    timeLimit: 26,
    starThresholds: [100, 80],
    reward: { stars: 15, diamonds: 3 },
    unlockCost: 40,
    requiredLevel: 'world4-level2',
  },
  {
    id: 'world4-level4',
    worldId: 'world4',
    order: 4,
    name: '三位数减法',
    description: '三位数 - 三位数',
    difficulty: 'SUB3to3',
    questionCount: 12,
    timeLimit: 26,
    starThresholds: [100, 80],
    reward: { stars: 18, diamonds: 4 },
    unlockCost: 60,
    requiredLevel: 'world4-level3',
  },
  {
    id: 'world4-level5',
    worldId: 'world4',
    order: 5,
    name: '三位数加减BOSS',
    description: '三位数加减综合（加法）',
    difficulty: 'ADD3to3',
    questionCount: 15,
    timeLimit: 22,
    starThresholds: [90, 75],
    reward: { stars: 30, diamonds: 8 },
    unlockCost: 100,
    requiredLevel: 'world4-level4',
  },

  // ===== 世界5：三位数乘除（规律） =====
  {
    id: 'world5-level1',
    worldId: 'world5',
    order: 1,
    name: '三位数乘法（规律）',
    description: '三位数 × 整十/整百/11',
    difficulty: 'MULTIPLY_3_PATTERN',
    questionCount: 15,
    timeLimit: 28,
    starThresholds: [100, 80],
    reward: { stars: 20, diamonds: 5 },
    unlockCost: 0,
  },
  {
    id: 'world5-level2',
    worldId: 'world5',
    order: 2,
    name: '三位数除法（规律）',
    description: '三位数 ÷ 整十/整除',
    difficulty: 'DIVIDE_3_PATTERN',
    questionCount: 15,
    timeLimit: 28,
    starThresholds: [100, 80],
    reward: { stars: 22, diamonds: 5 },
    unlockCost: 50,
    requiredLevel: 'world5-level1',
  },
  {
    id: 'world5-level3',
    worldId: 'world5',
    order: 3,
    name: '规律乘法进阶',
    description: '三位数规律乘法（速度）',
    difficulty: 'MULTIPLY_3_PATTERN',
    questionCount: 15,
    timeLimit: 24,
    starThresholds: [100, 80],
    reward: { stars: 25, diamonds: 6 },
    unlockCost: 100,
    requiredLevel: 'world5-level2',
  },
  {
    id: 'world5-level4',
    worldId: 'world5',
    order: 4,
    name: '规律除法进阶',
    description: '三位数规律除法（速度）',
    difficulty: 'DIVIDE_3_PATTERN',
    questionCount: 15,
    timeLimit: 24,
    starThresholds: [90, 75],
    reward: { stars: 30, diamonds: 8 },
    unlockCost: 150,
    requiredLevel: 'world5-level3',
  },
  {
    id: 'world5-level5',
    worldId: 'world5',
    order: 5,
    name: '规律终极BOSS',
    description: '三位数乘除综合（规律）',
    difficulty: 'MULTIPLY_3_PATTERN',
    questionCount: 25,
    timeLimit: 20,
    starThresholds: [85, 70],
    reward: { stars: 50, diamonds: 15 },
    unlockCost: 250,
    requiredLevel: 'world5-level4',
  },
]

// ==================== 角色配置 ====================
export const CHARACTERS: Character[] = [
  {
    id: 'meiledi',
    name: '美乐蒂',
    emoji: '🐰',
    description: '可爱的粉色小兔，稳定发挥！',
    cost: 0,
    bonus: 'extra_time',
    bonusValue: 0,
  },
  {
    id: 'bear',
    name: '小棕熊',
    emoji: '🐻',
    description: '每题额外+3秒思考时间',
    cost: 20,
    bonus: 'extra_time',
    bonusValue: 3,
  },
  {
    id: 'fox',
    name: '智慧狐狸',
    emoji: '🦊',
    description: 'Combo奖励效果+50%',
    cost: 40,
    bonus: 'combo_boost',
    bonusValue: 0.5,
  },
  {
    id: 'dragon',
    name: '数学龙',
    emoji: '🐉',
    description: '所有奖励+25%',
    cost: 80,
    bonus: 'reward_boost',
    bonusValue: 0.25,
  },
]

export function getWorldLevels(worldId: string): GameLevel[] {
  return GAME_LEVELS.filter(l => l.worldId === worldId).sort((a, b) => a.order - b.order)
}

export function getLevelById(levelId: string): GameLevel | undefined {
  return GAME_LEVELS.find(l => l.id === levelId)
}

export function getLevelStars(levelId: string, correct: number, total: number): 0 | 1 | 2 | 3 {
  const level = getLevelById(levelId)
  if (!level) return 0
  const rate = total > 0 ? (correct / total) * 100 : 0
  if (rate >= level.starThresholds[0]) return 3
  if (rate >= level.starThresholds[1]) return 2
  if (rate >= 50) return 1
  return 0
}

export function isLevelUnlocked(levelId: string, user: { levelProgress: Record<string, number> }): boolean {
  const level = getLevelById(levelId)
  if (!level) return false
  if (level.unlockCost === 0 && !level.requiredLevel) return true

  // 检查前置关卡
  if (level.requiredLevel) {
    const progress = user.levelProgress[level.worldId] || 0
    const requiredOrder = getLevelById(level.requiredLevel)?.order || 0
    if (progress < requiredOrder) return false
  }
  return true
}

export function getCharacterById(id: string): Character | undefined {
  return CHARACTERS.find(c => c.id === id)
}
